<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="alocalbox-20hb001uus" failures="1" tests="2" name="com.mycompany.vertxschematester.LmfInfoNGTest" time="0.013" errors="0" timestamp="2021-07-30T13:21:43 EDT" skipped="0">
  <testcase classname="com.mycompany.vertxschematester.LmfInfoNGTest" name="ClearArraysRequiredToHaveEntries" time="0.005">
    <failure message="failed to validate JSON!" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: failed to validate JSON!
at org.testng.Assert.fail(Assert.java:85)
at utils.TestUtil.assertSchema(TestUtil.java:68)
at com.mycompany.vertxschematester.LmfInfoNGTest.ClearArraysRequiredToHaveEntries(LmfInfoNGTest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.util.ConcurrentModificationException
at java.base/java.util.HashMap.forEach(HashMap.java:1339)
at io.vertx.json.schema.common.SchemaRouterImpl.lambda$getScopeParentAliases$10(SchemaRouterImpl.java:215)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at io.vertx.json.schema.common.SchemaRouterImpl.getScopeParentAliases(SchemaRouterImpl.java:215)
at io.vertx.json.schema.common.SchemaRouterImpl.resolveAbsoluteUriAlternatives(SchemaRouterImpl.java:227)
at io.vertx.json.schema.common.SchemaRouterImpl.lambda$resolveCachedSchema$3(SchemaRouterImpl.java:76)
at java.base/java.util.Optional.orElseGet(Optional.java:369)
at io.vertx.json.schema.common.SchemaRouterImpl.resolveCachedSchema(SchemaRouterImpl.java:76)
at io.vertx.json.schema.common.SchemaRouterImpl.resolveRef(SchemaRouterImpl.java:105)
at io.vertx.json.schema.common.RefSchema.validateAsync(RefSchema.java:64)
at io.vertx.json.schema.common.ItemsValidatorFactory$ItemsValidator.validateAsync(ItemsValidatorFactory.java:63)
at io.vertx.json.schema.common.SchemaImpl.runAsyncValidators(SchemaImpl.java:173)
at io.vertx.json.schema.common.SchemaImpl.validateAsync(SchemaImpl.java:121)
at io.vertx.json.schema.common.PropertiesValidatorFactory$PropertiesValidator.validateAsync(PropertiesValidatorFactory.java:171)
at io.vertx.json.schema.common.SchemaImpl.runAsyncValidators(SchemaImpl.java:173)
at io.vertx.json.schema.common.SchemaImpl.validateAsync(SchemaImpl.java:121)
at io.vertx.json.schema.common.SchemaImpl.validateAsync(SchemaImpl.java:48)
at com.mycompany.vertxschematester.JsonValidatorImpl.validate(JsonValidatorImpl.java:77)
at com.mycompany.vertxschematester.JsonValidatorImpl.validate(JsonValidatorImpl.java:52)
at utils.TestUtil.assertSchema(TestUtil.java:59)
... 39 more
]]>
    </failure>
  </testcase> <!-- ClearArraysRequiredToHaveEntries -->
  <system-out/>
  <testcase classname="com.mycompany.vertxschematester.LmfInfoNGTest" name="validate" time="0.008"/>
  <system-out/>
</testsuite> <!-- com.mycompany.vertxschematester.LmfInfoNGTest -->
